sudo: required
services:
  - docker

before_install:
  - docker build -t ImaTest123D/docker-react - f Dockerfile.dev .

script:
  - docker run ImaTest123D/docker-react npm run test -- --coverage

####